# fonts
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size       13
modify_font     strikethrough_position 110%
modify_font     strikethrough_thickness 160%
modify_font     underline_position 120%
modify_font     underline_thickness 1px
undercurl_style thin-dense

symbol_map U+276F,U+276E   FiraCode Nerd Font
# math glyphs
include symbol_map.conf

# key mappings
include keymaps.conf

# cursor
cursor_shape           beam
cursor_shape_unfocused hollow
cursor_blink_interval  0
cursor_trail           3

# scrollback
scrollbar_handle_opacity        0.3
scrollback_fill_enlarged_window yes
scrollback_pager                bat
scrollback_pager_history_size   8

# colorscheme
include                       kanagawa.conf
background_opacity            1
transparent_background_colors #1a1a22 #16161d #2a2a37 #363646

# tab bar
tab_bar_edge              top
tab_bar_align             left
tab_bar_style             custom
tab_activity_symbol       none
bell_on_tab               yes
tab_separator             "  "
tab_title_template        "{sup.index} {title}{bell_symbol}{activity_symbol} "
active_tab_title_template "{sup.index} {title}{bell_symbol}{activity_symbol} "
tab_bar_margin_width      0.0
tab_bar_margin_height     0.0 0.0

# mouse
mouse_hide_wait             1.0
pointer_shape_when_dragging hand
focus_follows_mouse yes

# urls
url_style            straight
open_url_with        $BROWSER
underline_hyperlinks hover

# behavior when pasting text
paste_actions confirm,confirm-if-large

# windows
active_border_color none
hide_window_decorations yes

# remote control
allow_remote_control yes
listen_on            unix:/tmp/mykitty

# disable stuff
enable_audio_bell no
confirm_os_window_close 0

# padding
window_padding_width 0
placement_strategy   bottom

# misc
notify_on_cmd_finish unfocused
shell_integration    no-title
paste_actions        quote-urls-at-prompt,confirm
foreground #ff0000
background #000000
