# global aliases
abbr -g "HGR"="--help 2>&1 | grep"
abbr -g "HG"="--help 2>&1 | grep"
abbr -g "C"="| wc -l"
abbr -g "L"="| less"
abbr -g "gr"="| rg"

abbr "v"="nvim"
abbr "_"="sudo"
abbr "__"="sudoedit"
abbr "+x"="chmod +x"

# git
abbr "g"="git"
abbr -g "git a"="git add"
abbr -g "git aa"="git add --all"
abbr -g "git b"="git branch"
abbr -g "git c"="git commit"
abbr -g "git m"="git commit -m \"%\""
abbr -g "git cm"="git commit -m \"%\""
abbr -g "git p"="git push"
abbr -g "git push f"="git push --force-with-lease"
abbr -g "git s"="git status"
abbr -g "git d"="git diff"
abbr -g "git cp"="git cherry-pick"
abbr -g "git rl"="git reflog"
abbr -g "git rh"="git reset --hard"
abbr -g "git rb"="git rebase"
abbr -g "git rbi"="git rebase --interactive"
abbr -g "git rbc"="git rebase --continue"
abbr -g "git rba"="git rebase --abort"
