CompileFlags:
  Add: [-Wall, -Wextra]

Completion:
  ArgumentLists: Delimiters

Hover:
  ShowAKA: true

Diagnostics:
  Suppress:
    - unused-parameter
    - sign-compare
    - c23-extensions

---
If:
  PathMatch: \.(cpp|hpp)$
CompileFlags:
  Add: [-std=c++26, -DLOCAL, -Wno-c23-extensions]
