Completion:
  ArgumentLists: Delimiters

Hover:
  ShowAKA: true

Diagnostics:
  Suppress:
    - unused-parameter
    - sign-compare
    - c23-extensions

CompileFlags:
  Add:
    - -Wall
    - -Wextra
    - -DLOCAL
