# Bar, wallpaper
exec-once = ~/.config/hypr/hyprland/scripts/start_geoclue_agent.sh
exec-once = runapp -- qs -c $qsConfig &
exec-once = ~/.config/hypr/custom/scripts/__restore_video_wallpaper.sh

# Clipboard: history
# exec-once = wl-paste --watch cliphist store &
exec-once = wl-paste --type text --watch bash -c 'cliphist store && qs -c $qsConfig ipc call cliphistService update'
exec-once = wl-paste --type image --watch bash -c 'cliphist store && qs -c $qsConfig ipc call cliphistService update'

# Background processes
exec-once = runapp -- ~/.config/hypr/hyprland/scripts/dispatch_browser_windows.sh
exec-once = runapp -- hyprsunset
exec-once = runapp -- safeeyes
exec-once = runapp -- niri-screen-time
exec-once = runapp -- udiskie
exec-once = runapp -- kmonad ~/.config/kmonad.kbd
