# Lines ending with `# [hidden]` won't be shown on cheatsheet
# Lines starting with #! are section headings

source = keybindings/shell.conf # must be on top
source = keybindings/utilities.conf
source = keybindings/window.conf
source = keybindings/workspace.conf
source = keybindings/session.conf
source = keybindings/screen.conf
source = keybindings/media.conf
source = keybindings/apps.conf

# Virtual machines
bind = Super+Alt, F1, exec, notify-send 'Entered Virtual Machine submap' 'Keybinds disabled. Hit Super+Alt+F1 to escape' -a 'Hyprland' && hyprctl dispatch submap virtual-machine # Disable keybinds
submap = virtual-machine
bind = Super+Alt, F1, exec, notify-send 'Exited Virtual Machine submap' 'Keybinds re-enabled' -a 'Hyprland' && hyprctl dispatch submap global # [hidden]
submap = global
