#!
source = keybindings/shell.conf
source = keybindings/utilities.conf
#!
source = keybindings/window.conf
#!
source = keybindings/workspace.conf
source = keybindings/session.conf
source = keybindings/screen.conf
#!
source = keybindings/media.conf
source = keybindings/apps.conf
source = keybindings/misc.conf
