#!/bin/bash

# colors
RED='\x1b[38;2;232;36;36m'    #e82424
BLUE='\x1b[38;2;126;156;216m' #7e9cd8
COLOR_RESET='\x1b[0m'

# find the firefox proile dir
if [[ -z "$WSLENV" ]]; then
	if [[ -d ${XDG_CONFIG_HOME:-$HOME/.config}/mozilla/firefox ]]; then
		FIREFOX_PROFILES_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/mozilla/firefox
	else
		FIREFOX_PROFILES_DIR=~/.mozilla/firefox
	fi
else
	# get the Windows username
	while true; do
		echo -en "${BLUE}What is your Windows username ? ${COLOR_RESET}"
		read -r win_username
		if [[ -n "$win_username" && -d "/mnt/c/Users/$win_username" ]]; then
			break
		else
			echo -e "${RED}Home directory not found. Try again...${COLOR_RESET}"
		fi
	done

	FIREFOX_PROFILES_DIR=/mnt/c/Users/"$win_username"/AppData/Roaming/Mozilla/Firefox/Profiles/
fi

# check there is at least one directory in $FIREFOX_PROFILES_DIR
exists_profile=false
for item in "$FIREFOX_PROFILES_DIR"/*; do
	if [[ -d "$item" && "$item" != "Crash Reports" && "$item" != "Pending Pings" && "$item" != "Profile Groups" ]]; then
		exists_profile=true
		break
	fi
done
$exists_profile || {
	echo -e "${RED}Where even is your Firefox profile ?${COLOR_RESET}"
	exit 1
}

# let the user select a profile through fzf
FIREFOX_PROFILE_DIR=$(
	fd --hidden --max-depth 1 -td . "$FIREFOX_PROFILES_DIR" |
		grep -v "Crash Reports" |
		grep -v "Pending Pings" |
		grep -v "Profile Groups" |
		fzf --select-1 --preview='eza -1alh --group-directories-first --color=always --icons {}'
)
if [[ -z "$FIREFOX_PROFILE_DIR" ]]; then
	echo -e "${RED}Please select a Firefox profile.${COLOR_RESET}"
	exit 1
fi

if [[ -z "$WSLENV" ]]; then
	# create symbolic links
	for item in ~/.config/browser/profile/*; do
		stripped="${item%/}" # strip trailing slash (if any)
		name="${stripped##*/}"
		[[ -e "$FIREFOX_PROFILE_DIR/$name" ]] && rm -rf "${FIREFOX_PROFILE_DIR:?}/$name"
		ln -s "$item" "$FIREFOX_PROFILE_DIR/$name"
	done
else
	# copy everything
	for item in ~/.config/browser/profile/*; do
		stripped="${item%/}" # strip trailing slash (if any)
		name="${stripped##*/}"
		[[ -e "$FIREFOX_PROFILE_DIR/$name" ]] && rm -rf "${FIREFOX_PROFILE_DIR:?}/$name"
		cp -r "$item" "$FIREFOX_PROFILE_DIR/$name" # use rsync instead ?
	done
fi
