local M = {}

M.symbols = {
	Array = "󰅪 ",
	Boolean = "󰨙 ",
	BreakStatement = "󰙧 ",
	CaseStatement = "󱃙 ",
	Call = "󰃹 ",
	Class = " ",
	Codeium = "󰘦 ",
	Collapsed = " ",
	Color = "󰏘 ",
	ContinueStatement = "→ ",
	Control = " ",
	Constant = "󰏿 ",
	Constructor = " ",
	Copilot = " ",
	Declaration = "󰙠 ",
	DoStatement = "󰑖 ",
	Delete = "󰩺 ",
	Enum = " ",
	EnumMember = "󰒻 ",
	Event = " ",
	Field = " ",
	File = " ", -- 󰈙
	Folder = " ",
	ForStatement = "󰑖 ",
	Function = "󰊕 ",
	H1Marker = "󰉫 ",
	H2Marker = "󰉬 ",
	H3Marker = "󰉭 ",
	H4Marker = "󰉮 ",
	H5Marker = "󰉯 ",
	H6Marker = "󰉰 ",
	Identifier = "󰀫 ",
	IfStatement = "󰇉 ",
	Interface = " ", -- 
	Key = "󰌋 ",
	Keyword = " ",
	List = "󰅪 ",
	Log = "󰦪 ",
	Lsp = " ",
	Macro = "󰁌 ",
	MarkdownH1 = "󰉫 ",
	MarkdownH2 = "󰉬 ",
	MarkdownH3 = "󰉭 ",
	MarkdownH4 = "󰉮 ",
	MarkdownH5 = "󰉯 ",
	MarkdownH6 = "󰉰 ",
	Method = " ",
	Module = "󰏗 ",
	Namespace = " ", -- 󰦮
	Null = "󰟢 ", -- 
	Number = "󰎠 ",
	Object = "󰅩 ",
	Operator = " ",
	Package = "󰏖 ", -- 
	Pair = "󰕘 ",
	Property = " ",
	Reference = " ",
	Regex = " ",
	Repeat = "󰑖 ",
	Scope = "󰅩 ",
	Specifier = " ",
	Statement = " ",
	Snippet = "󰩫 ", -- 󱄽
	String = "󰉾 ", -- 
	Struct = "󰌗 ", -- 󰆼
	SwitchStatement = "󰺟 ",
	Table = "󰅩 ",
	Terminal = " ",
	Text = " ",
	Type = " ",
	TypeParameter = "󰆩 ", -- 
	Unit = " ", -- 
	Value = "󰎠 ", -- 
	Variable = "󰀫 ",
	WhileStatement = "󰑖 ",
}

return M
