#!/bin/zsh

# Completions
zsh-users/zsh-completions kind:fpath path:src
Aloxaf/fzf-tab

# Prompt
romkatv/powerlevel10k
romkatv/zsh-no-ps2

# Utilities
romkatv/archive kind:path
romkatv/archive kind:fpath

# Features
zdharma-continuum/fast-syntax-highlighting
zsh-users/zsh-autosuggestions
zsh-users/zsh-history-substring-search
hlissner/zsh-autopair
