bind = Super, Return, exec, $TERMINAL                                            # Terminal emulator
bind = Super, E, exec, $TERMINAL --title "File manager" yazi ~/Téléchargements/  # File manager
bind = Super, B, exec, $BROWSER                                                  # Web browser
bind = Super, I, exec, qs -p ~/.config/quickshell/$qsConfig/settings.qml         # Settings
bind = Super, T, exec, $TERMINAL --class btop --title "Task Manager" btop        # Task manager
