# Zoom
binde = Super, Minus, exec, qs -c $qsConfig ipc call zoom zoomOut # Zoom out
binde = Super, Equal, exec, qs -c $qsConfig ipc call zoom zoomIn # Zoom in
binde = Super, Minus, exec, qs -c $qsConfig ipc call TEST_ALIVE || $scripts_dir/zoom.sh decrease 0.1 # [hidden] Zoom out
binde = Super, Equal, exec, qs -c $qsConfig ipc call TEST_ALIVE || $scripts_dir/zoom.sh increase 0.1 # [hidden] Zoom in
# Zoom with keypad
binde = Super, code:82, exec, qs -c $qsConfig ipc call zoom zoomOut # [hidden] Zoom out
binde = Super, code:86, exec, qs -c $qsConfig ipc call zoom zoomIn # [hidden] Zoom in
binde = Super, code:82, exec, qs -c $qsConfig ipc call TEST_ALIVE || $scripts_dir/zoom.sh decrease 0.1 # [hidden] Zoom out
binde = Super, code:86, exec, qs -c $qsConfig ipc call TEST_ALIVE || $scripts_dir/zoom.sh increase 0.1 # [hidden] Zoom in

# Color temperature
bindd = Super, F5, Color temperature down, exec, hyprctl hyprsunset temperature -50 # Color temperature down
bindd = Super, F6, Color temperature up, exec, hyprctl hyprsunset temperature +50 # Color temperature up
bindd = Super+Shift, F5, Blue light filter, exec, hyprctl hyprsunset temperature 2500 # Blue light filter
bindd = Super+Shift, F6, Color temperature reset, exec, hyprctl hyprsunset identity # Color temperature reset
