bindd = Super, Delete, Lock, exec, loginctl lock-session # Lock
bindld = Super+Shift, Delete, Suspend system, exec, systemctl suspend || loginctl suspend # Sleep
bindl=,switch:on:Lid Switch, exec, systemctl suspend || loginctl suspend # [hidden] Suspend when laptop lid is closed
bindd = Super+Ctrl+Shift+Alt, Delete, Shutdown, exec, systemctl poweroff || loginctl poweroff # Power off
