bindd = Super, Delete, Lock, exec, loginctl lock-session # Lock
bindld = Super+Shift, Delete, Suspend system, exec, systemctl suspend || loginctl suspend # Sleep
bindd = Super+Ctrl+Shift+Alt, Delete, Shutdown, exec, systemctl poweroff || loginctl poweroff # Power off
