bindd = Super, Delete, Lock, exec, loginctl lock-session # Lock
bindld = Super+Shift, Delete, Suspend system, exec, systemctl suspend || loginctl suspend # Sleep
bindl=,switch:on:Lid Switch, exec, systemctl suspend || loginctl suspend # [hidden] Suspend when laptop lid is closed, uncomment if for whatever reason it's not the default behavior
bindd = Ctrl+Shift+Alt+Super, Delete, Shutdown, exec, systemctl poweroff || loginctl poweroff # [hidden] Power off
