# Switching
#/# bind = Super, Hash,, # Focus workspace # (1, 2, 3,...)
# We use raw keycodes because some keyboard layouts register number keys as different chars. The codes can be verified with `wev`
bind = Super, code:10, exec, $scripts_dir/workspace_action.sh workspace 1 # [hidden]
bind = Super, code:11, exec, $scripts_dir/workspace_action.sh workspace 2 # [hidden]
bind = Super, code:12, exec, $scripts_dir/workspace_action.sh workspace 3 # [hidden]
bind = Super, code:13, exec, $scripts_dir/workspace_action.sh workspace 4 # [hidden]
bind = Super, code:14, exec, $scripts_dir/workspace_action.sh workspace 5 # [hidden]
bind = Super, code:15, exec, $scripts_dir/workspace_action.sh workspace 6 # [hidden]
bind = Super, code:16, exec, $scripts_dir/workspace_action.sh workspace 7 # [hidden]
bind = Super, code:17, exec, $scripts_dir/workspace_action.sh workspace 8 # [hidden]
bind = Super, code:18, exec, $scripts_dir/workspace_action.sh workspace 9 # [hidden]
bind = Super, code:19, exec, $scripts_dir/workspace_action.sh workspace 10 # [hidden]
# keypad numbers
bindp = Super, code:87, exec, $scripts_dir/workspace_action.sh workspace 1  # [hidden]
bindp = Super, code:88, exec, $scripts_dir/workspace_action.sh workspace 2  # [hidden]
bindp = Super, code:89, exec, $scripts_dir/workspace_action.sh workspace 3  # [hidden]
bindp = Super, code:83, exec, $scripts_dir/workspace_action.sh workspace 4  # [hidden]
bindp = Super, code:84, exec, $scripts_dir/workspace_action.sh workspace 5  # [hidden]
bindp = Super, code:85, exec, $scripts_dir/workspace_action.sh workspace 6  # [hidden]
bindp = Super, code:79, exec, $scripts_dir/workspace_action.sh workspace 7  # [hidden]
bindp = Super, code:80, exec, $scripts_dir/workspace_action.sh workspace 8  # [hidden]
bindp = Super, code:81, exec, $scripts_dir/workspace_action.sh workspace 9  # [hidden]
bindp = Super, code:90, exec, $scripts_dir/workspace_action.sh workspace 10 # [hidden]

#/# bind = Ctrl+Super, ←/→,, # Focus left/right
bind = Ctrl+Super, Right, workspace, r+1 # [hidden]
bind = Ctrl+Super, Left, workspace, r-1 # [hidden]
#/# bind = Ctrl+Super+Alt, ←/→,, # Focus busy left/right
bind = Ctrl+Super+Alt, Right, workspace, m+1 # [hidden]
bind = Ctrl+Super+Alt, Left, workspace, m-1 # [hidden]
#/# bind = Super, Page_↑/↓,, # Focus left/right
bind = Super, Page_Down, workspace, +1 # [hidden]
bind = Super, Page_Up, workspace, -1 # [hidden]
bind = Ctrl+Super, Page_Down, workspace, r+1 # [hidden]
bind = Ctrl+Super, Page_Up, workspace, r-1 # [hidden]
#/# bind = Super, Scroll ↑/↓,, # Focus left/right
bind = Super, mouse_up, workspace, +1 # [hidden]
bind = Super, mouse_down, workspace, -1 # [hidden]
bind = Ctrl+Super, mouse_up, workspace, r+1 # [hidden]
bind = Ctrl+Super, mouse_down, workspace, r-1 # [hidden]
## Special
bind = Super, S, togglespecialworkspace, # Toggle scratchpad
bind = Super, mouse:275, togglespecialworkspace, # [hidden]
bind = Ctrl+Super, BracketLeft, workspace, -1 # [hidden]
bind = Ctrl+Super, BracketRight, workspace, +1 # [hidden]
bind = Ctrl+Super, Up, workspace, r-5 # [hidden]
bind = Ctrl+Super, Down, workspace, r+5 # [hidden]
