[mgr]
cwd             = { fg = "#e6c384", bold = true }

find_keyword    = { fg = "#e82424" }
find_position   = {}

marker_copied   = { fg = "#98bb6c" }
marker_cut      = { fg = "#e46876" }
marker_marked   = { fg = "#957fb8" }
marker_selected = { fg = "#ffa066" }

count_copied    = { fg = "#1f1f28" }
count_cut       = { fg = "#1f1f28" }
count_selected  = { fg = "#1f1f28" }

border_symbol   = "│"
border_style    = { fg = "#54546d" }

syntect_theme   = "~/.config/bat/themes/Kanagawa/Kanagawa.tmTheme"

[indicator]
parent          = { bg = "#363646" }
current         = { bg = "#363646" }
preview         = { bold = true }

[tabs]
active          = { fg = "#1f1f28", bg = "#7e9cd8" }
inactive        = { fg = "#7e9cd8", bg = "#363646" }

[mode]
normal_main     = { fg = "#1f1f28", bg = "#7e9cd8" }
normal_alt      = { fg = "#9cabca", bg = "#54546d" }
select_main     = { fg = "#1f1f28", bg = "#957fb8" }
select_alt      = { fg = "#9cabca", bg = "#54546d" }
unset_main      = { fg = "#1f1f28", bg = "#dca561" }
unset_alt       = { fg = "#9cabca", bg = "#54546d" }

[status]
overall         = { fg = "#9cabca", bg = "#2a2a37" }
sep_left        = { open = "", close = "" }
sep_right       = { open = "", close = "" }

perm_type       = { fg = "#7e9cd8", bold = true }
perm_read       = { fg = "#e6c384" }
perm_write      = { fg = "#ff5d62" }
perm_exec       = { fg = "#7aa89f" }
perm_sep        = { fg = "#54546d" }

progress_label  = { fg = "#c8c093", bg = "#2a2a37", bold = true }
progress_normal = { fg = "#c8c093", bg = "#2a2a37" }
progress_error  = { fg = "#e82424", bg = "#2a2a37" }

[which]
cols            = 3
mask            = { bg = "#16161d" }
cand            = { fg = "#7e9cd8" }
rest            = { fg = "#727169" }
desc            = { fg = "#54546d" }
separator       = " ➜ "
separator_style = { fg = "#727169" }

[confirm]
border          = { fg = "#54546d" }
title           = { fg = "#54546d" }
content         = { fg = "#dcd7ba" }
list            = { fg = "#c8c093" }
btn_yes         = { bg = "#98bb6c", fg = "#1f1f28" }
btn_no          = { bg = "#e46876", fg = "#1f1f28" }
btn_labels      = ["[Y]es", "[N]o"]

[spot]
border          = { fg = "#54546d" }
title           = { fg = "#54546d" }
tbl_col         = { fg = "#9cabca" }
tbl_cell        = { fg = "#b8b4d0" }

[notify]
title_info      = { fg = "#6a9598" }
title_warn      = { fg = "#ff9e3b" }
title_error     = { fg = "#e82424" }

[pick]
border          = { fg = "#54546d" }
active          = { fg = "#957fb8", bold = true }
inactive        = {}

[input]
border          = { fg = "#54546d" }
title           = { fg = "#54546d" }
value           = {}
selected        = { reversed = true }

[cmp]
border          = { fg = "#54546d" }
active          = { reversed = true }
inactive        = {}
# icon_file       = ""
# icon_folder     = ""
# icon_command    = ""

[tasks]
border          = { fg = "#54546d" }
title           = { fg = "#54546d" }
hovered         = { fg = "#957fb8" }

[help]
on              = { fg = "#7aa89f" }
run             = { fg = "#957fb8" }
desc            = {}
hovered         = { reversed = true, bold = true }
footer          = { fg = "#1f1f28", bg = "#dcd7ba" }
icon_info       = { fg = "#6a9598" }
icon_warn       = { fg = "#ff9e3b" }
icon_error      = { fg = "#e82424" }

[filetype]
rules = [
	{ url = "*",  is = "hidden", fg = "#54546d" },
	{ url = "*/", is = "hidden", fg = "#54546d" },
	{ url = "*",  is = "block",  fg = "#e6c384" },
	{ url = "*",  is = "char",   fg = "#e6c384" },
	{ url = "*",  is = "exec",   fg = "#ff5d62" },
	{ url = "*",  is = "fifo",   fg = "#c0a36e" },
	{ url = "*",  is = "link",   fg = "#6a9598" },
	{ url = "*/", is = "link",   fg = "#6a9598" },
	{ url = "*",  is = "orphan", fg = "#e82424" },
	{ url = "*/", is = "orphan", fg = "#e82424" },
	{ url = "*",  is = "sock",   fg = "#957fb8" },
	{ url = "*",  is = "sticky", fg = "#7fb4ca" },
	{ url = "*/", is = "sticky", fg = "#7fb4ca" },
	{ url = "*/",                fg = "#7e9cd8" },
	{ url = "*",                 fg = "#dcd7ba" },
]

[icon]
prepend_dirs = [
	{ name = "Mathématiques", text = "󰩦" },
	{ name = "Informatique", text = "" },
	{ name = "Notes", text = "󰺿" },
	{ name = "Téléchargements", text = "" },
	{ name = "Médias", text = "󰸌" },
	{ name = "Images", text = "" },
	{ name = "Photos", text = "" },
	{ name = "Vidéos", text = "" },
	{ name = "Musique", text = "" },

	{ name = ".config", text = "" },
	{ name = ".git", text = "" },
	{ name = ".github", text = "" },
	{ name = ".npm", text = "" },
	{ name = "Desktop", text = "" },
	{ name = "Development", text = "" },
	{ name = "Documents", text = "" },
	{ name = "Downloads", text = "" },
	{ name = "Library", text = "" },
	{ name = "Movies", text = "" },
	{ name = "Music", text = "" },
	{ name = "Pictures", text = "" },
	{ name = "Public", text = "" },
	{ name = "Videos", text = "" },
]
prepend_conds = [
	# Special files
	{ if = "orphan", text = "", fg = "#b8b4d0" },
	{ if = "link", text = "", fg = "#b8b4d0" },
	{ if = "block", text = "" },
	{ if = "char", text = "" },
	{ if = "fifo", text = "" },
	{ if = "sock", text = "" },
	{ if = "sticky", text = "" },

	# fallback
	{ if = "dir",  text = "" },
	{ if = "exec", text = "", fg = "#4d5a5e" },
	{ if = "!dir", text = "" },
]
append_exts = [
	{ name = "asy", text = "󰒕", fg = "#ff0000" },
]
