$lock_cmd = hyprctl dispatch global quickshell:lock & pidof qs quickshell hyprlock || hyprlock
# $lock_cmd = pidof hyprlock || hyprlock
$suspend_cmd = systemctl suspend || loginctl suspend

general {
	lock_cmd = $lock_cmd
	before_sleep_cmd = loginctl lock-session
	after_sleep_cmd = hyprctl dispatch global quickshell:lockFocus
	inhibit_sleep = 3
}

listener {
	timeout = 600  # 10m
	on-timeout = brightnessctl set 15%- # decrease brightness
	on-resume  = brightnessctl -r       # restore brightness
}
listener {
	timeout = 600  # 10m
	on-timeout = brightnessctl -sd rgb:kbd_backlight set 0 # turn off keyboard backlight
	on-resume  = brightnessctl -rd rgb:kbd_backlight       # restore keyboard backlight
}

listener {
	timeout = 640  # 10m 40s
	on-timeout = loginctl lock-session
}
listener {
	timeout = 660  # 11m
	on-timeout = hyprctl dispatch dpms off
	on-resume  = hyprctl dispatch dpms on && brightnessctl -r
}

listener {
	timeout = 1800 # 30min
	on-timeout = $suspend_cmd # suspend system
}
