$lock_cmd = hyprctl dispatch global quickshell:lock & pidof qs quickshell hyprlock || hyprlock
# $lock_cmd = pidof hyprlock || hyprlock
$suspend_cmd = systemctl suspend || loginctl suspend

general {
	lock_cmd = $lock_cmd
	before_sleep_cmd = loginctl lock-session
	after_sleep_cmd = hyprctl dispatch global quickshell:lockFocus
	inhibit_sleep = 3
}

listener {
	timeout = 600 # 10m
	on-timeout = brightnessctl set 15%-
	on-resume = brightnessctl set 15%+
}

listener {
	timeout = 640 # 10m 40s
	on-timeout = loginctl lock-session && hyprctl dispatch dpms off
	on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

listener {
	timeout = 670 # 11m 10s
	on-timeout = $suspend_cmd
}
