# characters
--prompt="❯ "
--pointer=""
--marker="● "

# user interface
--style=full
--no-scrollbar

# kebindings
--bind=tab:toggle+up
--bind=btab:toggle+down
--bind=ctrl-a:select-all
--bind=ctrl-d:deselect-all
--bind=ctrl-t:toggle-all
--bind=ctrl-j:down
--bind=ctrl-k:up

# miscellaneous options
--cycle
--multi

# colors (needs to come last)
--color=fg:#dcd7ba,current-fg:#7aa89f,selected-fg:#7aa89f
--color=current-bg:#363646,gutter:#1f1f28
--color=border:#54546d,header:#727169
--color=hl:#e82424,marker:#d27e99
--color=info:#957fb8,spinner:#7E9CD8,prompt:#dca561

# preview
--preview="~/.local/bin/fzf_preview_wrapper {}"
--preview-window=45%
