################################################################################
# This is oly's configuration file.                                            #
# Please edit the following values.                                            #
# You must at least set author, base_path and pdf_viewer.                      #
################################################################################

# the author's name in the preview and generated pdf
author: Antoine Saez Dumas

# The base path where solutions are stored
base_path: ~/Mathématiques/Solutions

# the markup language the solutions are typed in
# must be one of latex or typst (default latex)
lang: typst

# language setting passed to the typst preview and preamble files.
# must be a two or three letters language code
language: fr

# the text editor to use
# autodected from $EDITOR and $VISUAL, fallback to vim
# editor: vim

# the pdf viewer used for 'oly gen'
pdf_viewer: zathura

# wether to open the generated pdf with pdf_viewer when running 'oly gen'
preview: true

# wether to confirm deletion or not in 'oly rm'
confirm: true

# map contest names to other ones
abbreviations:
  Shortlist: ISL

# directory structure to store contests
# available variables are: date, contest, year, problem and source
contest_format:
  Club: "Club/${date}"
  Test Novembre: "POFM/Tests/${year}/${contest} ${year}/${contest} ${year} ${problem}"
  Valbonne: "POFM/Valbonne/${year}/${source}"
  Cours en ligne: "POFM/Cours en ligne/${year}/${date}"
  Liste: "POFM/Listes/${source}"
  TN: "POFM/Vidéos/TN/${source}"
  Géo: "POFM/Vidéos/Géo/${source}"
  Alg: "POFM/Vidéos/Alg/${source}"
  Comb: "POFM/Vidéos/Comb/${source}"
  Envoi Géo: "../POFM/2025-2026/Envois/1. Géométrie/${source}"
  Envoi TN: "../POFM/2025-2026/Envois/2. Arithmétique/${source}"
  Envoi Alg: "../POFM/2025-2026/Envois/3. Algèbre/${source}"
  Envoi Combi: "../POFM/2025-2026/Envois/4. Combinatoire/${source}"
  Pot Pourri: "../POFM/2025-2026/Envois/5. Pot-Pourri/${source}"

# customize the colors used by the show command
colorscheme:
  math_mode: "#7fb4ca"
  operator: "#c0a36e"
  digit: "#d27e99"
  punctuation: "#9cabca"

# where to output the generated pdf
# defaults to ${XDG_CACHE_HOME:-~/.cache}/oly/${source}
# output_directory: ${PWD}/oly

# where temporary files are written
# defaults to ${TMPDIR:-/tmp}/oly
# OLY_TMPDIR: /tmp/oly

# added right after \documentclass in the preview file
# meant to specify which latex packages to use
packages: '\usepackage[french]{antoine}'

# You can also override preamble, contents, and metadata.
# preamble is what gets put in the preview file
# contents is the content that is already written in the file
# metadata is the metadata you get prompted for in 'oly add'
# For example, you can use the following
# metadata: "\
# source: ${source}\n\
# topic:  ${topic}\n\
# tags:   []\n\
# url:    \n\
# "
