################################################################################
# This is oly's configuration file.                                            #
# Please edit the following values.                                            #
# You must at least set author, base_path and pdf_viewer.                      #
################################################################################

# the author's name in the preview and generated pdfs
author: Antoine Saez Dumas

# the base path where solutions are stored
base_path: ~/Mathématiques/Solutions

# the path where figures are stored, inside of base_path
figures_dir: figures

# the markup language the solutions are typed in
# must be one of latex or typst (default latex)
lang: typst

# language setting passed to the typst preview and preamble files.
# must be a two or three letters language code
language: fr

# the text editor to use
# autodected from $EDITOR and $VISUAL, fallback to vim
# editor: vim

# the pdf viewer used for 'oly gen'
pdf_viewer: zathura

# wether to open the generated pdf with pdf_viewer when running 'oly gen'
open: true

# wether to confirm deletion or not in 'oly rm'
confirm: true

# map contest names to other ones
abbreviations:
    Shortlist: ISL

# directory structure to store contests
# available variables are: date, contest, year, problem and source
contest_format:
    Club: "Club/${date}"
    Test Novembre: "POFM/Tests/${year}/${contest} ${year}/${contest} ${year} ${problem}"
    Valbonne: "POFM/Valbonne/${contest} ${year}/${source}"
    Cours en ligne: "POFM/Cours en ligne/${year}/${date}"
    Liste: "POFM/Listes/${source}"
    TN: "POFM/Vidéos/TN/${source}"
    Géo: "POFM/Vidéos/Géo/${source}"
    Alg: "POFM/Vidéos/Alg/${source}"
    Comb: "POFM/Vidéos/Comb/${source}"

# customize the colors used by the show command
# see there for the full list of options:
# https://github.com/anonymousgrasshopper/oly/tree/main/include/oly/config.hpp#L55-L86
# you can generate a colorscheme from a (Neo)Vim one using 
# https://github.com/anonymousgrasshopper/oly/blob/main/assets/extras/get_nvim_colors.lua
colorscheme:
    constant: "#7e9cd8"
    markup.math: "#7fb4ca"

# where to output the generated pdf
# defaults to ${XDG_CACHE_HOME:-~/.cache}/oly/${source}
# output_directory: ${PWD}/oly

# where temporary files are written
# defaults to ${TMPDIR:-/tmp}/oly
# tmpdir: /tmp/oly

# added right after \documentclass in the preview file in latex
# meant to specify which latex packages to use
packages: '\usepackage[french]{antoine}'

# You can also override preview, contents, and metadata.
# preview is what gets put in the preview file
# contents is the initial content in a file opened through 'oly add'
# metadata is the metadata you get prompted for in 'oly add'
# For example, you can use the following
# metadata: "\
# source: ${source}\n\
# topic:  ${topic}\n\
# tags:   []\n\
# url:    \n\
# "
