#!/bin/zsh

START_TIME=2230
END_TIME=0500
INITIAL_SLEEP_DELAY=5
SLEEP_DELAY=0

function guard() {
	CURRENT_TIME=$(date +%H%M)

	# 10# forces base 10 parsing to avoid parsing as octal in some cases
	if [[ 10#$CURRENT_TIME -ge 10#$START_TIME ]] || [[ 10#$CURRENT_TIME -lt 10#$END_TIME ]]; then
		notify-send -u critical -i bed "Bedtime" "Going to sleep in $1 seconds"
		sleep $1
		systemctl sleep
		return 1
	else
		return 0
	fi
}

guard $INITIAL_SLEEP_DELAY

while true; do
	if guard $SLEEP_DELAY; then
		break
	fi
done
