#!/usr/bin/env zsh

if [[ -d $1 ]]; then
	eza -1al --git --group-directories-first --color=always --icons $1
elif [[ -f $1 ]]; then
	filetype=$(file --brief $1)
	case $filetype in
	*image*)
		kitty icat --clear --transfer-mode=stream --unicode-placeholder --stdin=no --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0 $1
		;;
	*text*)
		bat --plain --color=always "$1"
		;;
	*)
		hexyl --border=none --terminal-width=$FZF_PREVIEW_COLUMNS $1
		;;
	esac
elif [[ ${1:0:1} != "-" && -n $(printenv $1) ]]; then
	if [[ $1 == PATH ]]; then
		echo -e ${PATH//:/\\n}
	else
		printenv $1
	fi
elif type $1 >/dev/null 2>&1; then
	help=$($1 --help) && echo $help | bat --plain --language=help --paging=always
fi
