#!/usr/bin/env zsh

if [[ -d $1 ]]; then
	eza -1al --git --group-directories-first --color=always --icons $1
elif [[ -f $1 ]]; then
	filetype=$(file --mime-type --brief $1)
	case $filetype in
	*image*)
		kitty icat --clear --transfer-mode=stream --unicode-placeholder --stdin=no --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0 $1
		;;
	*text*)
		bat --plain --color=always "$1"
		;;
	*pdf*)
		pdftoppm -singlefile -jpeg -jpegopt quality=50 $1 |
			kitten icat --clear --transfer-mode=stream --unicode-placeholder --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0
		;;
	*)
		hexyl --border=none --terminal-width=$FZF_PREVIEW_COLUMNS $1
		;;
	esac
elif type $1 >/dev/null 2>&1; then
	( # search for --help flag in the file
		strings $(whence -p $word) | rg --quiet --fixed-strings -- "--help" &&
			# sandbox
			bwrap \
				--unshare-all \
				--ro-bind / / \
				--chdir $PWD \
				--tmpfs /tmp \
				--dev /dev \
				--proc /proc \
				--unshare-net \
				$word --help | bat --plain --language=help
	) ||
		(MANWIDTH=$FZF_PREVIEW_COLUMNS man $word 2>/dev/null | bat -plman --color=always) ||
		(out=which $word && echo $out) ||
		echo ${(P)word}
fi
