#!/usr/bin/env zsh

# colors
ERROR='\e[38;5;196m'
WARNING='\e[38;5;226m'
BLUE='\e[38;5;39m'
GREEN='\e[38;5;46m'
COLOR_RESET='\e[0m'

# clone the repo if it is not in ~/.config and cd to it
if [[ ! -d ~/.config/dotfiles ]]; then
	git clone https://github.com/antinomie8/dotfiles ~/.config/dotfiles
fi
if ! cd ~/.config/dotfiles; then
	echo "${ERROR}Cloning the GitHub repository failed. Check you internet connection and try again${COLOR_RESET}"
	exit
fi

# $1: file to copy (relative to ~/.config/dotfiles)
# $2: destination  (relative to ~/.config/dotfiles)
function copy() {
	if [[ ! -e $1 ]]; then
		echo -e "${WARNING} ${1/#$HOME/~} not found${COLOR_RESET}"
		return 1
	fi
	[[ -d $1 ]] && rsync -a --delete "$1/" $2/$(basename $1)/
	[[ -f $1 ]] && rsync -a --delete $1 $2/$(basename $1)
}
# $1: source base
# $2: destination base
# ${>=3}: items to copy from source to destination
function copy_group() {
	local src_base=$1 dst_base=$2
	shift 2
	for item in $@; do
		copy "$src_base/$item" "$dst_base"
	done
}

# lists of files to copy
configs=("asy" "bat" "btop" "browser" "clang-format" "clangd" "eza" "fastfetch" "git" "hypr"
	"hyprland-preview-share-picker" "illogical-impulse" "imv" "kitty" "lazygit" "mpv" "neomutt"
	"ncdu" "npm" "nvim" "oly" "quickshell" "ruff" "rustfmt" "safeeyes" "stylua" "tex-fmt" "thundery"
	"tmux" "udiskie" "uwsm" "wget" "xdg-desktop-portal" "xdg-desktop-portal-termfilechooser" "yazi"
	"zathura" "zsh" "fzf.conf" "kmonad.kbd" "mimeapps.list" "ripgrep.conf" "shellcheckrc" "user-dirs.dirs")
# mozilla msmtp notmuch goimapnotify himalaya mirador aerc
scripts=("assemble" "compile_sfml" "fzf_preview_wrapper" "git_dotfiles" "mailto" "rgb" "termsize" "zoxide-rename")
systemd_user_units=("mail-sync.service" "goimapnotify.service")
desktop_entries=("mail" "neomutt" "spotify" "yazi")

copy_group $HOME/.config configs $configs
copy_group $HOME/.local/bin scripts $scripts
copy_group $HOME/.config/systemd/user etc/systemd/user $systemd_user_units
copy_group $HOME/.local/share/applications etc/desktop ${desktop_entries[@]/%/.desktop}
copy $CPLUS_INCLUDE_PATH/dbg.h etc
copy $HOME/.local/share/texmf etc

# remove chosen files and directories
find configs/neomutt/accounts -regex '\S*@\S*\.\S*' -type f -delete
rm configs/quickshell/ii/.qmlls.ini
touch configs/quickshell/ii/.qmlls.ini
# obfuscate email adresses
[[ -f configs/neomutt/neomuttrc ]] && {
	sed -i \
		's:\(source .*/\)\S*@\S*\(<enter>;<check-stats>. "switch to \)\S*@\S*\("\):\2example@mail.com\2example@mail.com\3:' \
		configs/neomutt/neomuttrc
	sed -i 's:\(source .*/\)\S*@\S*\( # primary account\):\1example@mail.com\2:' configs/neomutt/neomuttrc
}
# obfuscate API keys
sed -i 's:\(export.*API_KEY=\).*:\1"ooops not supposed to show that":' configs/zsh/.zshenv

# cleanup
for file in configs/*; do
	if [[ ! $configs[(Ie)$file] ]]; then
		echo "${WARNING} ${GREEN}$file${BLUE} is in configs/ directory. Remove it ? ${COLOR_RESET}"
		read -r answer
		read -r answer
		case $answer in
		[yY][eE][sS] | [yY])
			rm -r configs/$file
			;;
		esac
	fi
done

# add everything to the index
git add .

# commit if args are passed to the scripts
if [[ $# == 2 ]]; then
	git commit -m $1 -m $2
	git push
elif [[ $# == 1 ]]; then
	git commit -m $1
	git push
fi
