#!/usr/bin/env bash

# colors
ERROR='\e[38;5;196m'
WARNING='\e[38;5;226m'
COLOR_RESET='\e[0m'

# clone the repo if it is not in ~/.config ans cd into it
[[ -d ~/.config/dotfiles ]] || git clone https://github.com/anonymousgrasshopper/dotfiles ~/.config/dotfiles
cd ~/.config/dotfiles || {
	echo "${ERROR}Cloning the GitHub repository failed. Check you internet connection and try again${COLOR_RESET}"
	exit
}

# $1: file to copy relative to ~/.config/dotfiles, $2: destination
function copy {
	[[ -e "$1" ]] || {
		echo -e "${WARNING} $1 not found${COLOR_RESET}"
		return 1
	}
	[[ -d "$1" ]] && rsync -a --delete "$1/" "$2/$(basename "$1")/"
	[[ -f "$1" ]] && rsync -a --delete "$1" "$2/$(basename "$1")"
}

# list of configs and scripts to copy
configs=("bat" "btop" "browser" "clangd" "eza" "fastfetch" "formatters" "git" "hypr"
	"hyprland-preview-share-picker" "illogical-impulse" "imv" "kitty" "kmonad" "lazygit"
	"mpv" "neomutt" "ncdu" "npm" "nvim" "oly" "quickshell" "texmf" "thundery" "tmux" "udiskie"
	"wget" "yazi" "zathura" "zsh" "fzf.conf" "mimeapps.list" "ripgrep.conf" " safeeyes"
	"shellcheckrc" "user-dirs.dirs" "xdg-desktop-portal" "xdg-desktop-portal-termfilechooser")
# mozilla msmtp notmuch imapnotify himalaya gh aerc atuin
scripts=("assemble" "fzf_preview_wrapper" "git_dotfiles" "rgb" "zoxide-rename")

# overwrite configs in the dotfiles repo
for config in ${configs[@]}; do
	copy "$HOME/.config/$config" configs
done
# overwrite scripts in the dotfiles repo
for script in ${scripts[@]}; do
	copy "$HOME/.local/bin/$script" scripts
done
# others
copy "$CPLUS_INCLUDE_PATH/dbg.hpp" etc
copy "$HOME/.local/share/typst/packages/local/oly" etc
fd . etc/oly -tf -e 'pdf' -x rm {}

# remove chosen files and directories
find configs/neomutt/accounts -regex "\S*@\S*\.\S*" -type f -delete
# obfuscate email adresses
[[ -f configs/neomutt/neomuttrc ]] && {
	sed -i 's:\(source .*/\)\S*@\S*\(<enter>;<check-stats>. "switch to \)\S*@\S*\("\):\2example@mail.com\2example@mail.com\3:' configs/neomutt/neomuttrc
	sed -i 's:\(source .*/\)\S*@\S*\( # primary account\):\1example@mail.com\2:' configs/neomutt/neomuttrc
}
# obfuscate API keys
sed -i 's:\(export.*API_KEY=\).*:\1"ooops not supposed to show that":' configs/zsh/.zshenv

# add everything to the index
git add .

# commit if args are passed to the scripts
if [[ $# == 2 ]]; then
	git commit -m"$1" -m"$2"
	git push
elif [[ $# == 1 ]]; then
	git commit -m"$1"
	git push
fi
