# Task Manager
windowrulev2 = float, center, size 900 600, rounding 0, bordercolor rgb(54546d), bordersize 2, class:^(Task Manager)$

# File manager
windowrulev2 = float, center, size 900 600, rounding 0, bordercolor rgb(54546d), bordersize 2, title:^(Open file)$
windowrulev2 = float, center, size 900 600, rounding 0, bordercolor rgb(54546d), bordersize 2, title:^(Open files)$
windowrulev2 = float, center, size 900 600, rounding 0, bordercolor rgb(54546d), bordersize 2, title:^(Open directory)$
windowrulev2 = float, center, size 900 600, rounding 0, bordercolor rgb(54546d), bordersize 2, title:^(Open directories)$
windowrulev2 = float, center, size 900 600, rounding 0, bordercolor rgb(54546d), bordersize 2, title:^(Save as)$
windowrulev2 = float, center, size 900 600, rounding 0, bordercolor rgb(54546d), bordersize 2, title:^(Save file)$
windowrulev2 = float, center, size 900 600, rounding 0, bordercolor rgb(54546d), bordersize 2, title:^(Save files)$
