# Task Manager
windowrule = match:title ^(Task Manager)$, float on, center on, size 893 600, rounding 0, border_color rgb(54546d), border_size 2

# File manager
windowrule = match:title ^(Open file)$, float on, center on, size 893 600, rounding 0, border_color rgb(54546d), border_size 2
windowrule = match:title ^(Open files)$, float on, center on, size 893 600, rounding 0, border_color rgb(54546d), border_size 2
windowrule = match:title ^(Open directory)$, float on, center on, size 893 600, rounding 0, border_color rgb(54546d), border_size 2
windowrule = match:title ^(Open directories)$, float on, center on, size 893 600, rounding 0, border_color rgb(54546d), border_size 2
windowrule = match:title ^(Save as)$, float on, center on, size 893 600, rounding 0, border_color rgb(54546d), border_size 2
windowrule = match:title ^(Save file)$, float on, center on, size 893 600, rounding 0, border_color rgb(54546d), border_size 2
windowrule = match:title ^(Save files)$, float on, center on, size 893 600, rounding 0, border_color rgb(54546d), border_size 2
